# Generated by Django 4.2.2 on 2023-07-06 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'City',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.CharField(max_length=20)),
                ('geometry', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, choices=[('adidas', 'Adidas'), ('apple', 'Apple'), ('armani', 'Armani'), ('bata', 'Bata'), ('benetton', 'Benetton'), ('bigbazaar', 'Bigbazaar'), ('blackberry', 'Blackberry'), ('calvinklein', 'Calvinklein'), ('celio', 'Celio'), ('chanel', 'Chanel')], max_length=100, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=100, null=True)),
                ('housenumber', models.CharField(blank=True, max_length=100, null=True)),
                ('suburb', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('opening_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('brand_wikipedia', models.TextField(blank=True, null=True)),
                ('description_de', models.TextField(blank=True, null=True)),
                ('operator', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brand_shops_dashboard.city')),
            ],
            options={
                'db_table': 'Brand',
            },
        ),
    ]
