# Generated by Django 4.2.2 on 2023-07-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_shops_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
