# Generated by Django 4.2.1 on 2023-07-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_shops_dashboard', '0003_alter_brand_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
